sql:
  hostname: "example"
  database: "example"
  user: "example"
  password: "example"

challonge:
  default_endpoint: "https://api.challonge.com/v1/tournaments/balkoura_1vs1_test/"
  key: "example"
