name: Java CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        java: [8, 11, 14]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1.3.0
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Gradle
        run: ./gradlew clean build
  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: BalkouraBattle
          path: build/libs/**
